version: '3.8'

services:
  schedule-sync:
    image: yapedro/sirius-schedule:latest
    container_name: sirius-schedule
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data

  schedule-sync-k0409:
    image: yapedro/sirius-schedule:latest
    container_name: sirius-schedule-k0409
    restart: unless-stopped
    env_file:
      - .env.k0409
    volumes:
      - ./data-k0409:/app/data

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: sirius-tunnel
    restart: unless-stopped
    command: tunnel --protocol http2 --config /etc/cloudflared/config.yml run
    volumes:
      - ~/.cloudflared:/etc/cloudflared:ro
      - ./cloudflared_config.yml:/etc/cloudflared/config.yml:ro
    depends_on:
      - schedule-sync
      - schedule-sync-k0409
