services:
  schedule-sync:
    image: yapedro/sirius-schedule:latest
    container_name: sirius-schedule
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data

  schedule-sync-k0409:
    image: yapedro/sirius-schedule:latest
    container_name: sirius-schedule-k0409
    restart: unless-stopped
    env_file:
      - .env.k0409
    volumes:
      - ./data-k0409:/app/data

  nginx:
    image: nginx:alpine
    container_name: sirius-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ~/my.crt:/etc/ssl/certs/fullchain.pem:ro
      - ~/my.key:/etc/ssl/private/privkey.pem:ro
    depends_on:
      - schedule-sync
      - schedule-sync-k0409
