server {
    listen 443 ssl;
    server_name schedule.ittori.ru;

    ssl_certificate /etc/ssl/certs/fullchain.pem;
    ssl_certificate_key /etc/ssl/private/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    resolver 127.0.0.11 valid=30s;

    location /k0409-24.ics {
        set $upstream_k0409 "http://sirius-schedule-k0409:8080";
        proxy_pass $upstream_k0409/k0409-24.ics;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        set $upstream_main "http://sirius-schedule:8080";
        proxy_pass $upstream_main/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

server {
    listen 80;
    server_name schedule.ittori.ru;
    return 301 https://$host$request_uri;
}
